//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StroopApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StroopApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StroopApp.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced settings.
        /// </summary>
        public static string Button_AdvancedSettings {
            get {
                return ResourceManager.GetString("Button_AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Button_Connect {
            get {
                return ResourceManager.GetString("Button_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with the same participant.
        /// </summary>
        public static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Button_Copy {
            get {
                return ResourceManager.GetString("Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Button_Disconnect {
            get {
                return ResourceManager.GetString("Button_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit application.
        /// </summary>
        public static string Button_ExitApplication {
            get {
                return ResourceManager.GetString("Button_ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Experiment.
        /// </summary>
        public static string Button_LaunchExperiment {
            get {
                return ResourceManager.GetString("Button_LaunchExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_Modify {
            get {
                return ResourceManager.GetString("Button_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New experiment.
        /// </summary>
        public static string Button_NewExperiment {
            get {
                return ResourceManager.GetString("Button_NewExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New export.
        /// </summary>
        public static string Button_NewExport {
            get {
                return ResourceManager.GetString("Button_NewExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the results folder.
        /// </summary>
        public static string Button_OpenExportFolder {
            get {
                return ResourceManager.GetString("Button_OpenExportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit application.
        /// </summary>
        public static string Button_Quit {
            get {
                return ResourceManager.GetString("Button_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit the application.
        /// </summary>
        public static string Button_Quit_With_Export {
            get {
                return ResourceManager.GetString("Button_Quit_With_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit application without export.
        /// </summary>
        public static string Button_Quit_Without_Export {
            get {
                return ResourceManager.GetString("Button_Quit_Without_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Button_Retry {
            get {
                return ResourceManager.GetString("Button_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Button_Send {
            get {
                return ResourceManager.GetString("Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupt the task.
        /// </summary>
        public static string Button_StopTask {
            get {
                return ResourceManager.GetString("Button_StopTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These words will always be written with ink of a different color than the meaning of the word..
        /// </summary>
        public static string Case1_P1_Congruence {
            get {
                return ResourceManager.GetString("Case1_P1_Congruence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the key corresponding to the color of the word&apos;s ink as quickly as possible, making the fewest mistakes..
        /// </summary>
        public static string Case1_P2_Instructions {
            get {
                return ResourceManager.GetString("Case1_P2_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These words will always be written in ink of the same color as the meaning of the word..
        /// </summary>
        public static string Case2_P1_Congruence {
            get {
                return ResourceManager.GetString("Case2_P1_Congruence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the key corresponding to the color of the word&apos;s ink as quickly as possible, making the fewest mistakes..
        /// </summary>
        public static string Case2_P2_Instructions {
            get {
                return ResourceManager.GetString("Case2_P2_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes, these words will be written in the same ink color as their meaning. Other times, these words will be written in a different ink color than their meaning..
        /// </summary>
        public static string Case3_P1_Congruence {
            get {
                return ResourceManager.GetString("Case3_P1_Congruence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the key matching the ink color as quickly as possible, making the fewest mistakes..
        /// </summary>
        public static string Case3_P2_Instructions {
            get {
                return ResourceManager.GetString("Case3_P2_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The words will always be displayed in a different color than their meaning..
        /// </summary>
        public static string Case4_P1_Congruence {
            get {
                return ResourceManager.GetString("Case4_P1_Congruence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the visual cue is a square, you should read the word. If the visual cue is a circle, you should name the color of the ink..
        /// </summary>
        public static string Case4_P2_Instructions {
            get {
                return ResourceManager.GetString("Case4_P2_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the key corresponding to the instruction as quickly as possible, making the fewest mistakes..
        /// </summary>
        public static string Case4_P2_InstructionsWithCue {
            get {
                return ResourceManager.GetString("Case4_P2_InstructionsWithCue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These words will always be written in ink of the same color as the meaning of the word..
        /// </summary>
        public static string Case5_P1_Congruence {
            get {
                return ResourceManager.GetString("Case5_P1_Congruence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore the visual cue..
        /// </summary>
        public static string Case5_P2_Instructions {
            get {
                return ResourceManager.GetString("Case5_P2_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the key corresponding to the meaning of the word, as quickly as possible, making the fewest mistakes..
        /// </summary>
        public static string Case5_P2_InstructionsWithCue {
            get {
                return ResourceManager.GetString("Case5_P2_InstructionsWithCue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes, these words will be written in the same ink color as their meaning. Other times, these words will be written in a different ink color than their meaning..
        /// </summary>
        public static string Case6_P1_Congruence {
            get {
                return ResourceManager.GetString("Case6_P1_Congruence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the visual cue is a square, you should read the word. If the visual cue is a circle, you should name the color of the ink..
        /// </summary>
        public static string Case6_P2_Instructions {
            get {
                return ResourceManager.GetString("Case6_P2_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the key corresponding to the instruction as quickly as possible, making the fewest mistakes..
        /// </summary>
        public static string Case6_P2_InstructionsWithCue {
            get {
                return ResourceManager.GetString("Case6_P2_InstructionsWithCue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add visual cue.
        /// </summary>
        public static string Check_AddPrime {
            get {
                return ResourceManager.GetString("Check_AddPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response.
        /// </summary>
        public static string Column_NoResponse {
            get {
                return ResourceManager.GetString("Column_NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the export folder for your results.
        /// </summary>
        public static string Description_ExportFolderDialog {
            get {
                return ResourceManager.GetString("Description_ExportFolderDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the export folder for the results..
        /// </summary>
        public static string Description_ExportFolderSelector {
            get {
                return ResourceManager.GetString("Description_ExportFolderSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the keys associated with the colors..
        /// </summary>
        public static string Description_KeyMapping {
            get {
                return ResourceManager.GetString("Description_KeyMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a participant to start the experiment..
        /// </summary>
        public static string Description_ParticipantManagement {
            get {
                return ResourceManager.GetString("Description_ParticipantManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To illustrate your parameters, a dynamic preview of the sequence of visual cues updates in real time based on your settings..
        /// </summary>
        public static string Description_PreviewIntroduction {
            get {
                return ResourceManager.GetString("Description_PreviewIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the profile to configure your experiment..
        /// </summary>
        public static string Description_ProfileManagement {
            get {
                return ResourceManager.GetString("Description_ProfileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during connection: {0}.
        /// </summary>
        public static string Error_ConnectionError {
            get {
                return ResourceManager.GetString("Error_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new experiment: {0}.
        /// </summary>
        public static string Error_CreatingNewExperiment {
            get {
                return ResourceManager.GetString("Error_CreatingNewExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during disconnection: {0}.
        /// </summary>
        public static string Error_DisconnectionError {
            get {
                return ResourceManager.GetString("Error_DisconnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This identifier is already used for another participant..
        /// </summary>
        public static string Error_DuplicateParticipantId {
            get {
                return ResourceManager.GetString("Error_DuplicateParticipantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed : {0}.
        /// </summary>
        public static string Error_ExportFailed {
            get {
                return ResourceManager.GetString("Error_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder or file does not exist.
        /// </summary>
        public static string Error_FileOrFolderNotFound {
            get {
                return ResourceManager.GetString("Error_FileOrFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill at least the ID field.
        /// </summary>
        public static string Error_FillIdField {
            get {
                return ResourceManager.GetString("Error_FillIdField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The averaging interval must be positive and divide the number of trials..
        /// </summary>
        public static string Error_GroupSizeInvalid {
            get {
                return ResourceManager.GetString("Error_GroupSizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This key is already used. Please choose another one..
        /// </summary>
        public static string Error_KeyMappingKeyUsed {
            get {
                return ResourceManager.GetString("Error_KeyMappingKeyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum response time must be positive..
        /// </summary>
        public static string Error_MaxResponseTimeInvalid {
            get {
                return ResourceManager.GetString("Error_MaxResponseTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No export folder configured..
        /// </summary>
        public static string Error_NoExportFolder {
            get {
                return ResourceManager.GetString("Error_NoExportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No port selected..
        /// </summary>
        public static string Error_NoPortSelected {
            get {
                return ResourceManager.GetString("Error_NoPortSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening file: {0}.
        /// </summary>
        public static string Error_OpeningFile {
            get {
                return ResourceManager.GetString("Error_OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This identifier is already in use for another participant..
        /// </summary>
        public static string Error_ParticipantIdAlreadyUsed {
            get {
                return ResourceManager.GetString("Error_ParticipantIdAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name cannot be empty or whitespace..
        /// </summary>
        public static string Error_ProfileNameEmpty {
            get {
                return ResourceManager.GetString("Error_ProfileNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A profile with this name already exists. Choose another name..
        /// </summary>
        public static string Error_ProfileNameExists {
            get {
                return ResourceManager.GetString("Error_ProfileNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a participant..
        /// </summary>
        public static string Error_SelectParticipant {
            get {
                return ResourceManager.GetString("Error_SelectParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a participant to delete !.
        /// </summary>
        public static string Error_SelectParticipantToDelete {
            get {
                return ResourceManager.GetString("Error_SelectParticipantToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a participant to modify!.
        /// </summary>
        public static string Error_SelectParticipantToModify {
            get {
                return ResourceManager.GetString("Error_SelectParticipantToModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an experiment profile..
        /// </summary>
        public static string Error_SelectProfile {
            get {
                return ResourceManager.GetString("Error_SelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a profile to delete !.
        /// </summary>
        public static string Error_SelectProfileToDelete {
            get {
                return ResourceManager.GetString("Error_SelectProfileToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a profile to modify!.
        /// </summary>
        public static string Error_SelectProfileToModify {
            get {
                return ResourceManager.GetString("Error_SelectProfileToModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task duration must be divisible by trial duration..
        /// </summary>
        public static string Error_TrialDurationNotDividingTaskDuration {
            get {
                return ResourceManager.GetString("Error_TrialDurationNotDividingTaskDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual cue duration must be greater than 0 !.
        /// </summary>
        public static string Error_VisualCueDurationInvalid {
            get {
                return ResourceManager.GetString("Error_VisualCueDurationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial duration must be positive and divide task duration..
        /// </summary>
        public static string Error_WordDurationInvalid {
            get {
                return ResourceManager.GetString("Error_WordDurationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Field_Age {
            get {
                return ResourceManager.GetString("Field_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Field_Gender {
            get {
                return ResourceManager.GetString("Field_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (cm).
        /// </summary>
        public static string Field_Height {
            get {
                return ResourceManager.GetString("Field_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Field_ID {
            get {
                return ResourceManager.GetString("Field_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string Field_ProfileName {
            get {
                return ResourceManager.GetString("Field_ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Field_Sex {
            get {
                return ResourceManager.GetString("Field_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task language.
        /// </summary>
        public static string Field_TaskLanguage {
            get {
                return ResourceManager.GetString("Field_TaskLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (kg).
        /// </summary>
        public static string Field_Weight {
            get {
                return ResourceManager.GetString("Field_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trials count.
        /// </summary>
        public static string Field_WordCount {
            get {
                return ResourceManager.GetString("Field_WordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string Header_Accuracy {
            get {
                return ResourceManager.GetString("Header_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Header_BlockNumber {
            get {
                return ResourceManager.GetString("Header_BlockNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congruence.
        /// </summary>
        public static string Header_Congruence {
            get {
                return ResourceManager.GetString("Header_Congruence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congruence (%).
        /// </summary>
        public static string Header_Congruence_Percent {
            get {
                return ResourceManager.GetString("Header_Congruence_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected answer.
        /// </summary>
        public static string Header_Expected_Answer {
            get {
                return ResourceManager.GetString("Header_Expected_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment profile.
        /// </summary>
        public static string Header_ExperimentProfile {
            get {
                return ResourceManager.GetString("Header_ExperimentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixation duration (ms).
        /// </summary>
        public static string Header_FixationDuration {
            get {
                return ResourceManager.GetString("Header_FixationDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given answer.
        /// </summary>
        public static string Header_Given_Answer {
            get {
                return ResourceManager.GetString("Header_Given_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaging interval.
        /// </summary>
        public static string Header_GroupSize {
            get {
                return ResourceManager.GetString("Header_GroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Header_Hours {
            get {
                return ResourceManager.GetString("Header_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max response time (ms).
        /// </summary>
        public static string Header_MaxResponseTime {
            get {
                return ResourceManager.GetString("Header_MaxResponseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average response time.
        /// </summary>
        public static string Header_MeanResponseTime {
            get {
                return ResourceManager.GetString("Header_MeanResponseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Header_Minutes {
            get {
                return ResourceManager.GetString("Header_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant ID.
        /// </summary>
        public static string Header_ParticipantId {
            get {
                return ResourceManager.GetString("Header_ParticipantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual cue duration (ms).
        /// </summary>
        public static string Header_PrimeDuration {
            get {
                return ResourceManager.GetString("Header_PrimeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string Header_ProfileName {
            get {
                return ResourceManager.GetString("Header_ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response validity.
        /// </summary>
        public static string Header_Response_Validity {
            get {
                return ResourceManager.GetString("Header_Response_Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response time (ms).
        /// </summary>
        public static string Header_ResponseTime {
            get {
                return ResourceManager.GetString("Header_ResponseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Header_Seconds {
            get {
                return ResourceManager.GetString("Header_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial ports.
        /// </summary>
        public static string Header_SerialPorts {
            get {
                return ResourceManager.GetString("Header_SerialPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch (%).
        /// </summary>
        public static string Header_Switch {
            get {
                return ResourceManager.GetString("Header_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial duration (ms).
        /// </summary>
        public static string Header_TrialDuration {
            get {
                return ResourceManager.GetString("Header_TrialDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trials.
        /// </summary>
        public static string Header_Trials {
            get {
                return ResourceManager.GetString("Header_Trials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of trials per block .
        /// </summary>
        public static string Header_TrialsPerBlock {
            get {
                return ResourceManager.GetString("Header_TrialsPerBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual cue type.
        /// </summary>
        public static string Header_Visual_Cue_Type {
            get {
                return ResourceManager.GetString("Header_Visual_Cue_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual cue.
        /// </summary>
        public static string Header_VisualCue {
            get {
                return ResourceManager.GetString("Header_VisualCue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual cue duration (ms).
        /// </summary>
        public static string Header_VisualCueDuration {
            get {
                return ResourceManager.GetString("Header_VisualCueDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial duration (ms).
        /// </summary>
        public static string Header_WordDuration {
            get {
                return ResourceManager.GetString("Header_WordDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add visual cue.
        /// </summary>
        public static string Label_AddPrime {
            get {
                return ResourceManager.GetString("Label_AddPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation mode.
        /// </summary>
        public static string Label_CalculationMode {
            get {
                return ResourceManager.GetString("Label_CalculationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string Label_Circle {
            get {
                return ResourceManager.GetString("Label_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle (%).
        /// </summary>
        public static string Label_CirclePercentage {
            get {
                return ResourceManager.GetString("Label_CirclePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct (%).
        /// </summary>
        public static string Label_CorrectPercentage {
            get {
                return ResourceManager.GetString("Label_CorrectPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant ID : {0}.
        /// </summary>
        public static string Label_CurrentParticipant {
            get {
                return ResourceManager.GetString("Label_CurrentParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task: {0}.
        /// </summary>
        public static string Label_CurrentProfile {
            get {
                return ResourceManager.GetString("Label_CurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Label_Disconnected {
            get {
                return ResourceManager.GetString("Label_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block completed.
        /// </summary>
        public static string Label_EndExperiment_BlockFinished {
            get {
                return ResourceManager.GetString("Label_EndExperiment_BlockFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block summary.
        /// </summary>
        public static string Label_EndExperiment_BlockSummary {
            get {
                return ResourceManager.GetString("Label_EndExperiment_BlockSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange history.
        /// </summary>
        public static string Label_ExchangeHistory {
            get {
                return ResourceManager.GetString("Label_ExchangeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results folder:.
        /// </summary>
        public static string Label_ExportFolderSelector_PathLabel {
            get {
                return ResourceManager.GetString("Label_ExportFolderSelector_PathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export in progress....
        /// </summary>
        public static string Label_ExportInProgress {
            get {
                return ResourceManager.GetString("Label_ExportInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key associated with the blue color:.
        /// </summary>
        public static string Label_KeyBlue {
            get {
                return ResourceManager.GetString("Label_KeyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key associated with the green color:.
        /// </summary>
        public static string Label_KeyGreen {
            get {
                return ResourceManager.GetString("Label_KeyGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key associated with the red color:.
        /// </summary>
        public static string Label_KeyRed {
            get {
                return ResourceManager.GetString("Label_KeyRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key associated with the yellow color:.
        /// </summary>
        public static string Label_KeyYellow {
            get {
                return ResourceManager.GetString("Label_KeyYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average for trials {0}–{1}:.
        /// </summary>
        public static string Label_LiveAverage {
            get {
                return ResourceManager.GetString("Label_LiveAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid data.
        /// </summary>
        public static string Label_LiveAverageNoData {
            get {
                return ResourceManager.GetString("Label_LiveAverageNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean.
        /// </summary>
        public static string Label_Mean {
            get {
                return ResourceManager.GetString("Label_Mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response.
        /// </summary>
        public static string Label_NoResponse {
            get {
                return ResourceManager.GetString("Label_NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview :.
        /// </summary>
        public static string Label_Overview {
            get {
                return ResourceManager.GetString("Label_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        public static string Label_Parity {
            get {
                return ResourceManager.GetString("Label_Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        public static string Label_PortConnected {
            get {
                return ResourceManager.GetString("Label_PortConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For associated publication with this rule, see Mangin et al.,.
        /// </summary>
        public static string Label_PublicationPrefix {
            get {
                return ResourceManager.GetString("Label_PublicationPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Label_ResponseCorrect {
            get {
                return ResourceManager.GetString("Label_ResponseCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        public static string Label_ResponseIncorrect {
            get {
                return ResourceManager.GetString("Label_ResponseIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response time: {0:N0} ms.
        /// </summary>
        public static string Label_ResponseTime {
            get {
                return ResourceManager.GetString("Label_ResponseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity unknown.
        /// </summary>
        public static string Label_ResponseValidityUnknown {
            get {
                return ResourceManager.GetString("Label_ResponseValidityUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results saved here.
        /// </summary>
        public static string Label_ResultsSavedHere {
            get {
                return ResourceManager.GetString("Label_ResultsSavedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of ports.
        /// </summary>
        public static string Label_SerialPortsList {
            get {
                return ResourceManager.GetString("Label_SerialPortsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string Label_Square {
            get {
                return ResourceManager.GetString("Label_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square (%).
        /// </summary>
        public static string Label_SquarePercentage {
            get {
                return ResourceManager.GetString("Label_SquarePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop bits.
        /// </summary>
        public static string Label_StopBits {
            get {
                return ResourceManager.GetString("Label_StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial: {0}.
        /// </summary>
        public static string Label_TrialNumber {
            get {
                return ResourceManager.GetString("Label_TrialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial range.
        /// </summary>
        public static string Label_TrialRange {
            get {
                return ResourceManager.GetString("Label_TrialRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2021.
        /// </summary>
        public static string Label_Year2021 {
            get {
                return ResourceManager.GetString("Label_Year2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2022.
        /// </summary>
        public static string Label_Year2022 {
            get {
                return ResourceManager.GetString("Label_Year2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Menu_Display {
            get {
                return ResourceManager.GetString("Menu_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Menu_Languages {
            get {
                return ResourceManager.GetString("Menu_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data has been successfully exported. Are you sure you want to exit the application?.
        /// </summary>
        public static string Message_ConfirmExitWithExport {
            get {
                return ResourceManager.GetString("Message_ConfirmExitWithExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the application without exporting the results? All non-exported data will be lost..
        /// </summary>
        public static string Message_ConfirmExitWithoutExport {
            get {
                return ResourceManager.GetString("Message_ConfirmExitWithoutExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting a new experiment will discard the current data. Do you want to continue?.
        /// </summary>
        public static string Message_ConfirmNewExperiment {
            get {
                return ResourceManager.GetString("Message_ConfirmNewExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this participant? Their data will be archived..
        /// </summary>
        public static string Message_DeleteParticipantConfirmation {
            get {
                return ResourceManager.GetString("Message_DeleteParticipantConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this profile?.
        /// </summary>
        public static string Message_DeleteProfileConfirmation {
            get {
                return ResourceManager.GetString("Message_DeleteProfileConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You have completed the experiment..
        /// </summary>
        public static string Message_EndInstructions {
            get {
                return ResourceManager.GetString("Message_EndInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved:
        ///{0}.
        /// </summary>
        public static string Message_Export_Completed {
            get {
                return ResourceManager.GetString("Message_Export_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export successful!.
        /// </summary>
        public static string Message_ExportSuccess {
            get {
                return ResourceManager.GetString("Message_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a key to define the mapping. Press Esc to cancel..
        /// </summary>
        public static string Message_KeyMapping {
            get {
                return ResourceManager.GetString("Message_KeyMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to stop the current task? Partial data can be exported..
        /// </summary>
        public static string Message_StopTask {
            get {
                return ResourceManager.GetString("Message_StopTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fixation cross will appear, followed by a color word..
        /// </summary>
        public static string Page1_Display_NoCue {
            get {
                return ResourceManager.GetString("Page1_Display_NoCue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fixation cross surrounded by a visual cue will appear, followed by a colored word..
        /// </summary>
        public static string Page1_Display_WithCue {
            get {
                return ResourceManager.GetString("Page1_Display_WithCue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example:.
        /// </summary>
        public static string Page1_Example {
            get {
                return ResourceManager.GetString("Page1_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will now begin a mental task..
        /// </summary>
        public static string Page1_Intro {
            get {
                return ResourceManager.GetString("Page1_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The words will be: RED, GREEN, BLUE, YELLOW..
        /// </summary>
        public static string Page1_WordsList {
            get {
                return ResourceManager.GetString("Page1_WordsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A visual cue will appear: a square means you must read the word, a circle means you must name the ink color..
        /// </summary>
        public static string Page2_CueExplanation {
            get {
                return ResourceManager.GetString("Page2_CueExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any questions before we begin?.
        /// </summary>
        public static string Page3_Questions {
            get {
                return ResourceManager.GetString("Page3_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Placeholder_Search {
            get {
                return ResourceManager.GetString("Placeholder_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on task duration.
        /// </summary>
        public static string Radio_TaskDuration {
            get {
                return ResourceManager.GetString("Radio_TaskDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on trial count.
        /// </summary>
        public static string Radio_WordCount {
            get {
                return ResourceManager.GetString("Radio_WordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment Configuration.
        /// </summary>
        public static string Title_ConfigPage {
            get {
                return ResourceManager.GetString("Title_ConfigPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new experiment.
        /// </summary>
        public static string Title_ConfirmNewExperiment {
            get {
                return ResourceManager.GetString("Title_ConfirmNewExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm shutdown.
        /// </summary>
        public static string Title_ConfirmShutDown {
            get {
                return ResourceManager.GetString("Title_ConfirmShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm task interruption.
        /// </summary>
        public static string Title_ConfirmStopTask {
            get {
                return ResourceManager.GetString("Title_ConfirmStopTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment dashboard.
        /// </summary>
        public static string Title_Dashboard {
            get {
                return ResourceManager.GetString("Title_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        public static string Title_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Title_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of experiment.
        /// </summary>
        public static string Title_EndInstructions {
            get {
                return ResourceManager.GetString("Title_EndInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment details.
        /// </summary>
        public static string Title_ExperimentDetails {
            get {
                return ResourceManager.GetString("Title_ExperimentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroop Experiment.
        /// </summary>
        public static string Title_ExperimentWindow {
            get {
                return ResourceManager.GetString("Title_ExperimentWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export completed.
        /// </summary>
        public static string Title_Export_Completed {
            get {
                return ResourceManager.GetString("Title_Export_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results folder.
        /// </summary>
        public static string Title_ExportFolderSelector {
            get {
                return ResourceManager.GetString("Title_ExportFolderSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment tracking.
        /// </summary>
        public static string Title_GraphsView {
            get {
                return ResourceManager.GetString("Title_GraphsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key mappings.
        /// </summary>
        public static string Title_KeyMapping {
            get {
                return ResourceManager.GetString("Title_KeyMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit mapping for {0}.
        /// </summary>
        public static string Title_KeyMappingDialog {
            get {
                return ResourceManager.GetString("Title_KeyMappingDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average times by interval.
        /// </summary>
        public static string Title_MeanByInterval {
            get {
                return ResourceManager.GetString("Title_MeanByInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant information.
        /// </summary>
        public static string Title_ParticipantDetails {
            get {
                return ResourceManager.GetString("Title_ParticipantDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit participant.
        /// </summary>
        public static string Title_ParticipantEditorWindow {
            get {
                return ResourceManager.GetString("Title_ParticipantEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant.
        /// </summary>
        public static string Title_ParticipantManagement {
            get {
                return ResourceManager.GetString("Title_ParticipantManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Window.
        /// </summary>
        public static string Title_ParticipantWindow {
            get {
                return ResourceManager.GetString("Title_ParticipantWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string Title_ProfileEditorWindow {
            get {
                return ResourceManager.GetString("Title_ProfileEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment profile.
        /// </summary>
        public static string Title_ProfileManagement {
            get {
                return ResourceManager.GetString("Title_ProfileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected profile details.
        /// </summary>
        public static string Title_ProfileManagementDetails {
            get {
                return ResourceManager.GetString("Title_ProfileManagementDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Title_Progress {
            get {
                return ResourceManager.GetString("Title_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Toggle_Off {
            get {
                return ResourceManager.GetString("Toggle_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string Toggle_On {
            get {
                return ResourceManager.GetString("Toggle_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets how many words are grouped to calculate an average response time. For example, a factor of 5 will show an average every 5 words..
        /// </summary>
        public static string Tooltip_AveragingInterval {
            get {
                return ResourceManager.GetString("Tooltip_AveragingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the proportion of congruent trials in the block. A trial is congruent when its meaning matches its color (e.g. the word Red written in red). Example: 25% = 75% incongruent, 25% congruent..
        /// </summary>
        public static string Tooltip_Congruence {
            get {
                return ResourceManager.GetString("Tooltip_Congruence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the visual cue is a circle, respond by naming the color of the word..
        /// </summary>
        public static string Tooltip_CueCircleResponse {
            get {
                return ResourceManager.GetString("Tooltip_CueCircleResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the visual cue is a square, respond by reading the word..
        /// </summary>
        public static string Tooltip_CueSquareResponse {
            get {
                return ResourceManager.GetString("Tooltip_CueSquareResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupt the running task and keep the partial data..
        /// </summary>
        public static string Tooltip_StopTask {
            get {
                return ResourceManager.GetString("Tooltip_StopTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines how often the visual cue changes between two trials. A switch is a transition from square to circle or vice versa. Example: 100% = alternation each trial, 0% = always the same shape..
        /// </summary>
        public static string Tooltip_Switch {
            get {
                return ResourceManager.GetString("Tooltip_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} ms.
        /// </summary>
        public static string Value_LiveAverage {
            get {
                return ResourceManager.GetString("Value_LiveAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLUE.
        /// </summary>
        public static string Word_BLUE {
            get {
                return ResourceManager.GetString("Word_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREEN.
        /// </summary>
        public static string Word_GREEN {
            get {
                return ResourceManager.GetString("Word_GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RED.
        /// </summary>
        public static string Word_RED {
            get {
                return ResourceManager.GetString("Word_RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YELLOW.
        /// </summary>
        public static string Word_YELLOW {
            get {
                return ResourceManager.GetString("Word_YELLOW", resourceCulture);
            }
        }
    }
}
