name: .NET CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore StroopApp.sln

    - name: Build
      run: dotnet build StroopApp.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test StroopApp.sln --no-build --configuration Release --verbosity normal

    - name: Publish self-contained single EXE
      run: |
        dotnet publish StroopApp/StroopApp.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

    - name: Upload single-file EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: StroopApp-standalone-exe
        path: StroopApp/bin/Release/net8.0-windows/win-x64/publish/StroopApp.exe
